### ISSUE TITLE
Inclusion in F-Droid

### ISSUE THREAD

**Issue by Poussinou** [dynamitetuning/com.dynamite.heaterrc#14]
Hi,

Since this app is GNU GPL v2 licensed, are you considering the fact to add it to [F-Droid](https://f-droid.org/)? There is a strong community behind.

You can find some documentation [here](https://f-droid.org/docs/).

Otherwise, if you don't want to work on the inclusion of this app by yourself, would it be ok for you if someone else do it for you?

**Comment by dynamitetuning** [comment]
I had it already on f-droid, but then it got removed for some reason. I have also tried to re-submit a request for inclusion, but without success so far (see [here](https://gitlab.com/fdroid/rfp/issues/527#note_66064109)).
If you want, you may try your luck.
