### ISSUE TITLE
Wrong event notification

### ISSUE THREAD

**Issue by tacarrie** [dynamitetuning/com.dynamite.heaterrc#3]
It happened a couple of times, that 24 hours after the last correctly scheduled message has been sent, the app brings the event notification that another message has been sent, even if it was not scheduled. The message is not sent in that case, but the notification is confusing and should be avoided.

No clue how to reproduce. Uninstall / Install the app solved the problem.

**Comment by dynamitetuning** [comment]
I was able to reproduce the issue. Now I just need to find where the bug is hidden.

**Comment by dynamitetuning** [comment]
Bug found. I mistakenly used the "setRepeating" instead of "set" method. Will be fixed with the next release.

**Comment by dynamitetuning** [comment]
Issue is fixed with v1.5.
