### ISSUE TITLE
FR: Extend the Help

### ISSUE THREAD

**Issue by tacarrie** [dynamitetuning/com.dynamite.heaterrc#5]
Currently the text shown when pressing the Help button is quite simple and basic.
It would be better to have an extended Help text which explains all of the functions and possibilities the app has to offer.
Instead of having the text built in the app, it could also be a link to an external website (or github wiki) where the help text is shown.

**Comment by dynamitetuning** [comment]
Will be implemented with the next release, using the Wiki on this page as link.
